// C1 THE NIGHT WATCHMAN — the signing tool. The operator's deliberate act that turns an
// inert contracts/<id>.json into an executable, signed contract. It computes the signature
// over the canonical JSON and stamps it into contracts/<id>.md, preserving the human
// charter body above the signature block. Editing the JSON afterwards invalidates the
// signature (the runner will REFUSE it) until it is signed again — that is the point.
//
// Usage:
//   node contracts/sign.mjs <id>                      (re)sign the current JSON
//   node contracts/sign.mjs <id> --mode armed         set mode, then sign (flip log-only OFF)
//   node contracts/sign.mjs <id> --mode log-only      set mode back to log-only, then sign
//   node contracts/sign.mjs <id> --signer "name"      record who signed
import fs from 'node:fs';
import { contractPath, signaturePath, loadContract, signatureFor } from './lib.mjs';

const args = process.argv.slice(2);
const id = args.find((a) => !a.startsWith('--'));
const opt = (name) => { const i = args.indexOf(`--${name}`); return i >= 0 ? args[i + 1] : null; };
if (!id) { console.error('usage: node contracts/sign.mjs <id> [--mode armed|log-only] [--signer "name"]'); process.exit(1); }

const contract = loadContract(id);

// optional: change the mode as part of signing (flipping log-only is a signed decision).
const mode = opt('mode');
if (mode) {
  if (!['armed', 'log-only'].includes(mode)) { console.error(`--mode must be armed|log-only, got "${mode}"`); process.exit(1); }
  contract.mode = mode;
  fs.writeFileSync(contractPath(id), JSON.stringify(contract, null, 2) + '\n');
  console.log(`mode set to "${mode}" in ${id}.json`);
}

const signer = opt('signer') || `operator (${(contract.mailer && contract.mailer.to) || 'vishnumovva@icloud.com'})`;
const signedAt = new Date().toISOString();
const sig = signatureFor(contract);

// preserve an existing charter body (everything above a previous "## SIGNATURE" marker).
let charter = '';
try {
  const existing = fs.readFileSync(signaturePath(id), 'utf8');
  charter = existing.split(/\n#+\s*SIGNATURE/i)[0].trimEnd() + '\n';
} catch { /* no existing md — a charter must be authored separately; write a stub header */ }
if (!charter.trim()) charter = `# ${contract.title || id} — CONTRACT\n\n(Charter text not found — add the operator's mandate above the signature block.)\n`;

const block = [
  '',
  '## SIGNATURE',
  '',
  'This block is generated by `contracts/sign.mjs`. It binds the charter above to the exact',
  `bytes of \`${id}.json\`. The runner executes this contract ONLY while the signature matches.`,
  '',
  '```',
  `contract: ${id}.json`,
  `mode: ${contract.mode || 'log-only'}`,
  `signer: ${signer}`,
  `signed-at: ${signedAt}`,
  `signature: ${sig}`,
  '```',
  '',
].join('\n');

fs.writeFileSync(signaturePath(id), charter + block);
console.log(`signed ${id}: ${sig}`);
console.log(`  signer: ${signer}`);
console.log(`  mode:   ${contract.mode || 'log-only'}`);
console.log(`  → ${signaturePath(id)}`);
